#!/usr/bin/env node
/**
 * MCP Tools Test — call each registered tool once via stdio MCP client and write MCP_TOOLS_REPORT.md
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { EXPECTED_TOOLS, getExpectedToolsCount, readVersion, ROOT } from "./lib/shared.mjs";
import {
  buildSmokeEnv,
  listMcpServerTargets,
  summarizeToolResult,
  withMcpClient,
} from "./lib/mcp-client.mjs";

const version = readVersion();
const runDir = join(tmpdir(), `marketing-brain-mcp-tools-${Date.now()}`);
mkdirSync(runDir, { recursive: true });

const env = buildSmokeEnv({
  // Isolate JSON stores for this run (packages use os.homedir defaults; we still avoid clobbering via tmp cwd)
});

const DEMO_SNAPSHOT = {
  campaignId: "camp-smoke-001",
  name: "Smoke Campaign",
  channel: "meta",
  spend: 1000,
  impressions: 50000,
  clicks: 1200,
  conversions: 40,
  revenue: 5000,
  periodStart: "2026-07-01",
  periodEnd: "2026-07-31",
};

/** Build ordered test calls; stateful helpers receive prior results. */
function buildToolPlan(pkg) {
  /** @type {Record<string, (ctx: Record<string, unknown>) => { name: string, arguments: Record<string, unknown> }[]>} */
  const plans = {
    "@mcp-marketing/google-ads": () => [
      { name: "list_campaigns", arguments: {} },
      { name: "get_campaign", arguments: { campaign_id: "1001" } },
      {
        name: "create_campaign",
        arguments: { name: "MCP Smoke Campaign", budget_micros: 1_000_000, channel_type: "SEARCH" },
      },
      { name: "pause_campaign", arguments: { campaign_id: "1001" } },
      { name: "enable_campaign", arguments: { campaign_id: "1001" } },
      { name: "update_budget", arguments: { campaign_id: "1001", budget_micros: 2_000_000 } },
      { name: "search_keywords", arguments: { query: "marketing automation", limit: 5 } },
      { name: "campaign_report", arguments: { date_range: "LAST_30_DAYS" } },
      { name: "list_customers", arguments: {} },
      { name: "account_info", arguments: {} },
    ],
    "@mcp-marketing/meta-ads": () => [
      { name: "list_campaigns", arguments: {} },
      {
        name: "create_campaign",
        arguments: { name: "Meta Smoke", objective: "OUTCOME_TRAFFIC", daily_budget: 50 },
      },
      { name: "pause_campaign", arguments: { campaign_id: "2001" } },
      { name: "resume_campaign", arguments: { campaign_id: "2001" } },
      { name: "update_budget", arguments: { campaign_id: "2001", daily_budget: 80 } },
      {
        name: "create_audience",
        arguments: { name: "Smoke Audience", subtype: "CUSTOM", approximate_count: 1000 },
      },
      {
        name: "create_ad",
        arguments: {
          name: "Smoke Ad",
          campaign_id: "2001",
          creative_body: "Try Marketing Brain",
        },
      },
      { name: "get_metrics", arguments: { campaign_id: "2001" } },
    ],
    "@mcp-marketing/whatsapp": () => [
      {
        name: "send_birthday_message",
        arguments: { to: "+5511999999999", name: "Smoke User", couponCode: "SMOKE10" },
      },
      {
        name: "send_coupon",
        arguments: { to: "+5511999999999", couponCode: "SAVE20", discount: "20% OFF" },
      },
      {
        name: "send_campaign",
        arguments: {
          to: "+5511999999999",
          campaignId: "camp-smoke",
          message: "Smoke campaign message",
        },
      },
      {
        name: "send_template",
        arguments: {
          to: "+5511999999999",
          templateName: "hello_world",
          templateParams: ["Smoke"],
        },
      },
      {
        name: "schedule_message",
        arguments: {
          to: "+5511999999999",
          body: "Scheduled smoke message",
          scheduledAt: new Date(Date.now() + 3600_000).toISOString(),
        },
      },
      {
        name: "order_confirmation",
        arguments: {
          to: "+5511999999999",
          orderId: "ORD-SMOKE-1",
          total: "R$ 99,90",
          items: ["Item A"],
        },
      },
    ],
    "@mcp-marketing/insights": () => [
      {
        name: "analyze_insights",
        arguments: { snapshots: [DEMO_SNAPSHOT] },
      },
      { name: "get_health_scores", arguments: {} },
      { name: "list_recommendations", arguments: {} },
      { name: "get_executive_dashboard", arguments: {} },
      { name: "list_timeline_events", arguments: { limit: 10 } },
      {
        name: "record_timeline_event",
        arguments: {
          type: "smoke_test",
          title: "MCP tools smoke",
          description: "Generated by npm run mcp:tools",
          campaignId: "camp-smoke-001",
        },
      },
      { name: "get_health_center", arguments: {} },
      { name: "generate_report", arguments: { format: "json" } },
    ],
    "@mcp-marketing/ai-agent": () => [
      { name: "chat", arguments: { message: "hello", sessionId: "smoke-session" } },
      {
        name: "chat",
        arguments: { message: "please pause campaign Brand Awareness", sessionId: "smoke-session" },
      },
      { name: "list_pending_approvals", arguments: {} },
      { name: "get_agent_history", arguments: { sessionId: "smoke-session", limit: 20 } },
      { name: "get_ai_summary", arguments: {} },
      { name: "list_audit_logs", arguments: { limit: 20 } },
      // confirm/cancel filled dynamically after pending list
    ],
    "@mcp-marketing/workflows": () => [
      { name: "list_workflows", arguments: {} },
      {
        name: "create_workflow",
        arguments: {
          name: "Smoke Workflow",
          description: "Created by mcp:tools",
          trigger: { type: "manual" },
          steps: [{ type: "noop", name: "Start", config: {} }],
          status: "active",
        },
      },
      { name: "list_workflow_templates", arguments: {} },
      {
        name: "create_workflow_from_template",
        arguments: { templateId: "tpl-birthday", name: "Birthday Smoke", status: "draft" },
      },
      { name: "run_due_workflows", arguments: {} },
      { name: "list_workflow_executions", arguments: { limit: 20 } },
      { name: "list_workflow_audit_logs", arguments: { limit: 20 } },
    ],
  };

  return plans[pkg]?.() ?? EXPECTED_TOOLS[pkg].map((name) => ({ name, arguments: {} }));
}

function parseJsonFromResult(result) {
  const text = (result?.content ?? [])
    .filter((p) => p.type === "text")
    .map((p) => p.text)
    .join("");
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

const targets = listMcpServerTargets();
/** @type {Array<{ package: string, tool: string, status: string, ms: number, result: string }>} */
const rows = [];
let failed = false;

console.log("MCP Tools Test (stdio callTool)");
console.log("===============================");
console.log(`Temp dir: ${runDir}`);

for (const target of targets) {
  const expected = EXPECTED_TOOLS[target.name] ?? [];
  const plan = buildToolPlan(target.name);

  const outcome = await withMcpClient(
    target,
    async (client) => {
      /** @type {Array<{ tool: string, status: string, ms: number, result: string }>} */
      const local = [];
      const ctx = {};

      const calls = [...plan];

      // Dynamic AI agent confirm/cancel after creating pending action
      if (target.name === "@mcp-marketing/ai-agent") {
        // plan already has chats + list; we inject confirm/cancel mid-flight
      }

      for (const call of calls) {
        const started = performance.now();
        try {
          const result = await client.callTool({
            name: call.name,
            arguments: call.arguments,
          });
          const ms = Math.round(performance.now() - started);
          const status = result.isError ? "ERROR" : "PASS";
          if (status === "ERROR") {
            failed = true;
          }
          local.push({
            tool: call.name,
            status,
            ms,
            result: summarizeToolResult(result),
          });

          if (call.name === "chat") {
            const parsed = parseJsonFromResult(result);
            if (parsed?.pendingAction?.id) {
              ctx.pendingActionId = parsed.pendingAction.id;
            }
          }
          if (call.name === "list_pending_approvals") {
            const parsed = parseJsonFromResult(result);
            const pending = parsed?.pending ?? [];
            if (pending[0]?.id) {
              ctx.pendingActionId = pending[0].id;
            }
          }
          if (call.name === "create_workflow" || call.name === "create_workflow_from_template") {
            const parsed = parseJsonFromResult(result);
            if (parsed?.workflow?.id) {
              ctx.workflowId = parsed.workflow.id;
              if (!ctx.firstWorkflowId) {
                ctx.firstWorkflowId = parsed.workflow.id;
              }
            }
          }
          if (call.name === "run_workflow") {
            const parsed = parseJsonFromResult(result);
            if (parsed?.execution?.id) {
              ctx.executionId = parsed.execution.id;
            }
          }
        } catch (error) {
          const ms = Math.round(performance.now() - started);
          failed = true;
          local.push({
            tool: call.name,
            status: "FAIL",
            ms,
            result: error instanceof Error ? error.message : String(error),
          });
        }
      }

      // AI agent: confirm + cancel with real ids
      if (target.name === "@mcp-marketing/ai-agent") {
        const pendingId = ctx.pendingActionId;
        for (const [tool, args] of [
          ["confirm_action", { actionId: pendingId ?? "missing-action" }],
          [
            "chat",
            {
              message: "please launch campaign Summer Sale",
              sessionId: "smoke-session-2",
            },
          ],
        ]) {
          const started = performance.now();
          try {
            const result = await client.callTool({ name: tool, arguments: args });
            const ms = Math.round(performance.now() - started);
            if (tool === "chat") {
              const parsed = parseJsonFromResult(result);
              if (parsed?.pendingAction?.id) {
                ctx.cancelActionId = parsed.pendingAction.id;
              }
            }
            const status = result.isError ? "ERROR" : "PASS";
            if (status === "ERROR") failed = true;
            local.push({ tool, status, ms, result: summarizeToolResult(result) });
          } catch (error) {
            failed = true;
            local.push({
              tool,
              status: "FAIL",
              ms: Math.round(performance.now() - started),
              result: error instanceof Error ? error.message : String(error),
            });
          }
        }

        const cancelId = ctx.cancelActionId ?? "missing-cancel";
        const started = performance.now();
        try {
          const result = await client.callTool({
            name: "cancel_action",
            arguments: { actionId: cancelId },
          });
          const ms = Math.round(performance.now() - started);
          const status = result.isError ? "ERROR" : "PASS";
          if (status === "ERROR") failed = true;
          local.push({
            tool: "cancel_action",
            status,
            ms,
            result: summarizeToolResult(result),
          });
        } catch (error) {
          failed = true;
          local.push({
            tool: "cancel_action",
            status: "FAIL",
            ms: Math.round(performance.now() - started),
            result: error instanceof Error ? error.message : String(error),
          });
        }
      }

      // Workflows: stateful follow-ups
      if (target.name === "@mcp-marketing/workflows") {
        const workflowId = ctx.firstWorkflowId ?? ctx.workflowId;
        const followUps = [
          {
            name: "update_workflow",
            arguments: { workflowId, name: "Smoke Workflow Updated", status: "active" },
          },
          { name: "duplicate_workflow", arguments: { workflowId } },
          { name: "run_workflow", arguments: { workflowId } },
          { name: "pause_workflow", arguments: { workflowId } },
          {
            name: "recover_workflow_execution",
            arguments: { executionId: "nonexistent-execution" },
          },
          { name: "delete_workflow", arguments: { workflowId } },
        ];

        for (const call of followUps) {
          const started = performance.now();
          try {
            const result = await client.callTool({
              name: call.name,
              arguments: call.arguments,
            });
            const ms = Math.round(performance.now() - started);
            // recover with missing id is expected ERROR from tool — still a successful MCP round-trip
            const expectError = call.name === "recover_workflow_execution";
            const status = result.isError
              ? expectError
                ? "PASS"
                : "ERROR"
              : "PASS";
            if (status === "ERROR") failed = true;
            local.push({
              tool: call.name,
              status,
              ms,
              result: summarizeToolResult(result) || (expectError ? "expected missing execution" : "ok"),
            });
          } catch (error) {
            // SDK may throw on tool handler errors depending on version
            const ms = Math.round(performance.now() - started);
            const expectError = call.name === "recover_workflow_execution";
            const status = expectError ? "PASS" : "FAIL";
            if (status === "FAIL") failed = true;
            local.push({
              tool: call.name,
              status,
              ms,
              result: error instanceof Error ? error.message : String(error),
            });
          }
        }
      }

      return local;
    },
    env,
  );

  if (!outcome.ok) {
    failed = true;
    for (const tool of expected) {
      rows.push({
        package: target.name,
        tool,
        status: "FAIL",
        ms: 0,
        result: `server init: ${outcome.error}`,
      });
    }
    console.log(`FAIL ${target.name} — ${outcome.error}`);
    continue;
  }

  for (const row of outcome.result) {
    rows.push({ package: target.name, tool: row.tool, status: row.status, ms: row.ms, result: row.result });
    console.log(
      `${row.status} ${target.name}::${row.tool} (${row.ms}ms) — ${row.result.slice(0, 80)}`,
    );
  }

  // Ensure every expected tool appears at least once
  for (const tool of expected) {
    if (!rows.some((r) => r.package === target.name && r.tool === tool)) {
      failed = true;
      rows.push({
        package: target.name,
        tool,
        status: "FAIL",
        ms: 0,
        result: "tool was not invoked",
      });
    }
  }
}

const uniqueTools = new Set(rows.filter((r) => r.status !== "FAIL" || r.result !== "tool was not invoked").map((r) => `${r.package}::${r.tool}`));
const passCount = rows.filter((r) => r.status === "PASS").length;
const errorCount = rows.filter((r) => r.status === "ERROR").length;
const failCount = rows.filter((r) => r.status === "FAIL").length;

const lines = [
  "# MCP Tools Report",
  "",
  `**Product:** Marketing Brain v${version} LTS`,
  `**Generated:** ${new Date().toISOString()}`,
  `**Expected tools:** ${getExpectedToolsCount()}`,
  `**Calls recorded:** ${rows.length}`,
  `**PASS:** ${passCount} · **ERROR:** ${errorCount} · **FAIL:** ${failCount}`,
  "",
  "> Test harness uses placeholder credentials and `WHATSAPP_STUB=true` (no live network).",
  "",
  "| Package | Tool | Status | Time (ms) | Result |",
  "|---------|------|--------|----------:|--------|",
];

for (const row of rows) {
  const safeResult = row.result.replace(/\|/g, "\\|").replace(/\n/g, " ");
  lines.push(
    `| \`${row.package}\` | \`${row.tool}\` | ${row.status} | ${row.ms} | ${safeResult} |`,
  );
}

lines.push("", "## Summary by package", "");
for (const [pkg, tools] of Object.entries(EXPECTED_TOOLS)) {
  const pkgRows = rows.filter((r) => r.package === pkg);
  const statuses = tools.map((tool) => {
    const match = pkgRows.find((r) => r.tool === tool && r.status === "PASS")
      ?? pkgRows.find((r) => r.tool === tool);
    return `- \`${tool}\`: ${match?.status ?? "MISSING"} (${match?.ms ?? 0}ms)`;
  });
  lines.push(`### ${pkg}`, "", ...statuses, "");
}

lines.push(
  "## Criterion",
  "",
  `- Servers started via stdio MCP client: ${targets.every((t) => t.entry) ? "yes" : "no"}`,
  `- Tools covered: ${uniqueTools.size}`,
  `- Report generated: yes`,
  "",
);

const outputPath = join(ROOT, "MCP_TOOLS_REPORT.md");
writeFileSync(outputPath, `${lines.join("\n")}\n`);
console.log(`\nWrote ${outputPath}`);

if (failed) {
  console.error("\nMCP tools test finished with failures.");
  process.exit(1);
}

console.log("\nMCP tools test passed.");
