console.log("Marketing Brain Workflows Runner (stub)");
console.log("=======================================");
console.log("");
console.log("Workflows MCP exposes tools for creating and running marketing automations.");
console.log("");
console.log("How to run:");
console.log("  1. npm run build");
console.log("  2. npm run start:workflows");
console.log("  3. Connect your MCP client to the Workflows server");
console.log("");
console.log("Useful tools:");
console.log("  - list_workflows");
console.log("  - create_workflow");
console.log("  - run_workflow");
console.log("  - run_due_workflows");
console.log("");
console.log("CLI:");
console.log("  marketing-brain start");
console.log("  npm run workflows:run");
